import { useEffect, useState, memo } from "react";
import { useRouter } from "next/router";
import MarkdownIt from "markdown-it";
import Head from "next/head";
import moment from "moment";
import axios from "axios";
import Hero from "../components/hero";


const Article = () => {

    const router = useRouter();

    const md = new MarkdownIt({html: true});

    const { id } = router.query;
    
    const [post, setPost] = useState({attributes: {}});
    
    useEffect(() => {
        
        axios.get(`http://localhost:1337/api/posts/${id}`).then(res => setPost(res.data.data));
        
    }, []);

    var htmlContent;

    if (post.attributes.content) {
        htmlContent = md.render(post.attributes.content);
    }

    return (

        <div className="px-24">

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero />

            <div className="px-28 my-14">
                <span className="text-gray-400 font-regular text-sm mb-2">{moment(post.attributes.createdAt).format('LL')}</span>
                <h1 className="text-slate-900 font-bold text-2xl">{post.attributes.title}</h1>

                <section className="space-y-6 mt-20" dangerouslySetInnerHTML={{__html: htmlContent}}></section>
            </div>


        </div>

    );

}


export default memo(Article);