import { useEffect, useState, memo } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import moment from "moment";
import axios from "axios";
import Hero from "../components/hero";


const Article = () => {

    const router = useRouter();

    const { id } = router.query;
    
    const [loading, setLoading] = useState(true);
    const [content, setContent] = useState({});
    const [post, setPost] = useState({attributes: {}});
    
    useEffect(() => {
        
        axios.get(`http://localhost:1337/api/posts/${id}`).then(({data}) => {
            setPost(data.data);
            setContent(JSON.parse(data.data.attributes.content));
            setLoading(false);
        });
        
    }, []);
    
    const returnContent = (item, key) => {

        if (item.type === "header") {
            return (
                <h1 className="font-bold text-slate-900 text-3xl">{item.data.text}</h1>
            )
        }

        if (item.type === "paragraph") {
            return (
                <p className="font-regular text-slate-500 text-base">{item.data.text}</p>
            )
        }

        if (item.type === "image") {
            return (
                <img className="" src={`http://localhost:1337${item.data.file.url}`} />
            )
        }

        if (item.type === "list") {
            return (
                <ul className="p-4">
                    {item.data.items.map((items, key) => 
                        <li className="font-regular text-slate-500 list-disc text-base">{items}</li>
                    )}
                </ul>
            )
        }

    } 

    return (

        <div className="px-24">

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero />

            {
                loading ?
                <p>Cargando...</p>
                :
                <div className="px-28 my-14">
                    <span className="text-slate-400 font-regular text-sm mb-2">{moment(post.attributes.createdAt).format('LL')}</span>

                    <section className="space-y-6">

                        {
                            content.blocks.map((item, key) => 
                                returnContent(item, key)
                            )
                        }

                    </section>

                </div>
            }

        </div>

    );

}


export default memo(Article);