import Head from "next/head";


const Home = () => {

    const test = [1, 2, 3, 4, 5];
    const test2 = [1, 2, 3, 4];

    return (

        <div className="px-24">

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="bg-black p-10 rounded-b-md">
                <h1 className="font-extrabold text-white text-9xl">THE BLOG</h1>
            </header>

            <article className="cursor-pointer rounded-md p-6 hover:bg-gray-100 grid grid-cols-6 my-14">
                <img className="col-span-3 rounded-md w-full" src="https://via.placeholder.com/1080x720" alt="" />

                <div className="col-span-3 px-10 my-auto">
                    <span className="text-gray-400 font-regular text-sm">january 15, 2020</span>
                    <h2 className="text-black font-bold my-2 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit.</h2>
                    <p className="text-gray-500 font-regular text-base">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero consequatur eius amet ipsa accusantium voluptas, sapiente omnis cumque fugiat iure quam expedita tempore hic eaque praesentium nulla ipsum assumenda officiis?</p>
                </div>
            </article>

            <section>

                <p className="text-black font-bold text-base">Latest articles</p>

                <div className="mt-6 space-y-4">

                    {test.map(item =>

                        <div key={item} className="rounded-md hover:bg-gray-100 cursor-pointer flex p-2">
                            <img className="rounded-md w-14" src="https://via.placeholder.com/150" alt="" />

                            <div className="ml-4">
                                <h2 className="font-medium text-black text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h2>
                                <p className="text-gray-400 text-sm">january 15, 2020</p>
                            </div>
                        </div>

                    )}

                </div>

            </section>

            <section className="my-14">

                <p className="text-black font-bold text-base">Editor's Pick</p>

                <div className="mt-6 grid grid-cols-4 gap-2">

                    {test2.map(item =>

                        <div key={item} className="rounded-md space-y-4 hover:bg-gray-100 cursor-pointer flex flex-col p-2">

                            <img className="rounded-md mx-auto" src="https://via.placeholder.com/1080x720" alt="" />

                            <span className="text-gray-400 text-xs">january 15, 2020</span>
                            <h2 className="font-medium text-black text-lg">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h2>
                            <p className="text-gray-400 text-sm">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni quod quos beatae iure praesentium natus ratione quaerat ut, sequi a expedita neque maiores et officia? Odio laborum cum molestiae sed?</p>

                        </div>

                    )}

                </div>

            </section>

            <section className="my-14">

                <p className="text-black font-bold text-base">More articles</p>

                <div className="mt-6 flex flex-col space-y-4">

                    {test.map(item =>

                        <div key={item} className="rounded-md hover:bg-gray-100 cursor-pointer flex p-2">
                            <img className="rounded-md w-1/4" src="https://via.placeholder.com/1080x720" alt="" />

                            <div className="ml-4  space-y-1">
                                <span className="text-gray-400 text-sm">january 15, 2020</span>
                                <h2 className="font-medium text-black text-lg">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h2>
                                <p className="text-gray-400 text-sm">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni quod quos beatae iure praesentium natus ratione quaerat ut, sequi a expedita neque maiores et officia? Odio laborum cum molestiae sed? Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae voluptates ex vel accusamus. Dolores asperiores hic possimus facere error repudiandae vitae, cum perferendis, sit, accusantium ullam quas quia numquam adipisci?</p>
                            </div>
                        </div>

                    )}

                </div>

            </section>

        </div>

    );

}


export default Home;